### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by krayc425** [songkuixi/TouchBreakout#2]
* Features
  * [x] Keyboard optimization
  * [ ] Pause function
  * [ ] Sound effects
  * [x] Velocity increase with scores
* Bugs
  * [ ] Sometimes ball run on a horizontal level endlessly
  * [x] Sometimes ball run in slow motion

**Comment by yuzhouzhuang** [comment]
@songkuixi Good Job!
